version: '3.8'

services:
  authentication-service:
    image: daver2910/authentication-service:latest
    restart: always
    ports:
      - 5101:5101
    environment:
      - PORT=5101
      - USER_SERVICE=http://user-service:5102
      - SECRET_KEY=david-is-cool
      - MONGODB_URI=mongodb+srv://Development:Password.0@cluster0.lpdtr.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
    networks:
      - internal_network

  user-service:
    image: daver2910/user-service:latest
    restart: always
    env_file:
      - internal.env
    environment:
      - PORT=5102
    networks:
      - internal_network

  go-solutions-gateway:
    image: daver2910/frida-gateway:latest
    restart: always
    ports:
      - 5200:5200
    env_file:
      - internal.env
    environment:
      - PORT=5200
      - USER_SERVICE=http://user-service:5102
    networks:
      - internal_network

  go-solutions-admin:
    image: daver2910/frida-admin:latest
    restart: always
    ports:
      - 5201:5201
    environment:
        - PORT=5201
        - REACT_APP_GATEWAY_URL=https://gateway.gosolutions.ie
        - REACT_APP_AUTH_URL=https://auth.gosolutions.ie
        - MONGODB_URI=mongodb+srv://Development:Password.0@cluster0.lpdtr.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

  go-solutions:
    image: daver2910/gosolutions:latest
    restart: always
    ports:
      - 5202:5202
    environment:
      - PORT=5202
      - REACT_APP_ENDPOINT=https://gateway.gosolutions.ie

networks:
  internal_network:
    driver: bridge
